# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstudy_py_sdk.models.solver_description_format import SolverDescriptionFormat

class TestSolverDescriptionFormat(unittest.TestCase):
    """SolverDescriptionFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSolverDescriptionFormat(self):
        """Test SolverDescriptionFormat"""
        # inst = SolverDescriptionFormat()

if __name__ == '__main__':
    unittest.main()
