# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstudy_py_sdk.api.thoth_engine_module_api import ThothEngineModuleApi


class TestThothEngineModuleApi(unittest.TestCase):
    """ThothEngineModuleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ThothEngineModuleApi()

    def tearDown(self) -> None:
        pass

    def test_v1_brief_answers_post(self) -> None:
        """Test case for v1_brief_answers_post

        Answers to all lists of each block
        """
        pass

    def test_v1_show_steps_post(self) -> None:
        """Test case for v1_show_steps_post

        All lists and all steps of all blocks
        """
        pass

    def test_v1_single_answer_post(self) -> None:
        """Test case for v1_single_answer_post

        First answer of the first block, text version
        """
        pass


if __name__ == '__main__':
    unittest.main()
