# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstudy_py_sdk.models.request_solve_request_v1_lang import RequestSolveRequestV1Lang

class TestRequestSolveRequestV1Lang(unittest.TestCase):
    """RequestSolveRequestV1Lang unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestSolveRequestV1Lang(self):
        """Test RequestSolveRequestV1Lang"""
        # inst = RequestSolveRequestV1Lang()

if __name__ == '__main__':
    unittest.main()
