# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstudy_py_sdk.models.v1_single_answer_post200_response import V1SingleAnswerPost200Response

class TestV1SingleAnswerPost200Response(unittest.TestCase):
    """V1SingleAnswerPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SingleAnswerPost200Response:
        """Test V1SingleAnswerPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SingleAnswerPost200Response`
        """
        model = V1SingleAnswerPost200Response()
        if include_optional:
            return V1SingleAnswerPost200Response(
                data = upstudy_py_sdk.models.solver/self_simple_response.solver.SelfSimpleResponse(
                    input = '', 
                    solution = upstudy_py_sdk.models.solution.solution(), ),
                err_msg = ''
            )
        else:
            return V1SingleAnswerPost200Response(
        )
        """

    def testV1SingleAnswerPost200Response(self):
        """Test V1SingleAnswerPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
