# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upstudy_py_sdk.models.v1_brief_answers_post200_response import V1BriefAnswersPost200Response

class TestV1BriefAnswersPost200Response(unittest.TestCase):
    """V1BriefAnswersPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1BriefAnswersPost200Response:
        """Test V1BriefAnswersPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1BriefAnswersPost200Response`
        """
        model = V1BriefAnswersPost200Response()
        if include_optional:
            return V1BriefAnswersPost200Response(
                data = upstudy_py_sdk.models.solver/self_brief_response.solver.SelfBriefResponse(
                    input = '', 
                    solutions = [
                        upstudy_py_sdk.models.solver/solution.solver.Solution(
                            block_name = upstudy_py_sdk.models.block_name.block_name(), 
                            results = [
                                upstudy_py_sdk.models.solver/step.solver.Step(
                                    children = [
                                        upstudy_py_sdk.models.solver/step.solver.Step(
                                            description = upstudy_py_sdk.models.description.description(), 
                                            image_url = '', 
                                            latex = '', )
                                        ], 
                                    description = upstudy_py_sdk.models.description.description(), 
                                    image_url = '', 
                                    latex = '', )
                                ], 
                            solution_name = upstudy_py_sdk.models.solution_name.solution_name(), )
                        ], ),
                err_msg = ''
            )
        else:
            return V1BriefAnswersPost200Response(
        )
        """

    def testV1BriefAnswersPost200Response(self):
        """Test V1BriefAnswersPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
