# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RequestSolveRequestV1Lang(str, Enum):
    """
    Output language enumeration values
    """

    """
    allowed enum values
    """
    EN = 'EN'
    RU = 'RU'
    PT = 'PT'
    ES = 'ES'
    HI = 'HI'
    FR = 'FR'
    PL = 'PL'
    KO = 'KO'
    JA = 'JA'
    ZHS = 'ZHS'
    ZHT = 'ZHT'
    VI = 'VI'
    IT = 'IT'
    DE = 'DE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RequestSolveRequestV1Lang from a JSON string"""
        return cls(json.loads(json_str))


